### ISSUE TITLE
User can start the quiz

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/PurrBreeds#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start the quiz.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive button that will start the quiz comprised of 10 cat breed guesses.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Start Screen](https://github.com/annaaksenov/ajax-project/assets/121647003/fcfa17b4-de7b-422a-835e-c2e42914b8c3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a HTML skeleton.
- [x] Create the app's main screen using CSS.
- [x] Title the name of the app "PurrBreeds".
- [x] Using CSS create the start button and name it "Give me a cat!".
- [x] Above the box have a text that says "Do you know your cats?".
- [x] Make sure that click target's a `<button>` elements.
- [x] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [x] Create a desktop view of the main screen.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
