### ISSUE TITLE
User can select best answer to the multiple-choice 

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/PurrBreeds#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select best answer.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Players can guess or test their knowledge on the provided cat's breed with multiple choice.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Guess the breed](https://github.com/annaaksenov/ajax-project/assets/121647003/4b12b7c7-8a5e-4150-a12f-0f1f4a1312b5)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When the user clicks "Give me a cat!" the view should swap to the quiz presenting the first quiz.
- [x] Using XMLHttpRequest, request 10 random breeds of cats from The Cat API and call it when the quiz begins.
- [x] Confirming the required data is received, create separate functions that will extract the image and breed's name.
- [x] User can see the provided cat image.
- [x] Below the image will be 3 multiple choice options to guess the breed with one being the corresponding breed to the image displayed.
- [x] Make sure that click targets are `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] If the user clicks the wrong choice, the background of the '<button>' will turn red.
- [x] If the the user clicks the correct choice the background of the '<button>' will turn green. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
