### ISSUE TITLE
User can confirm they were correct or guess again

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/PurrBreeds#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their correct answer.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The correct answer will display over the image and an arrow button to move on to the next image will appear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Reveal Breed](https://github.com/annaaksenov/PurrBreeds/assets/121647003/35e747eb-d4fc-40d5-b056-d567709c20da)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] The breed of the cat will display above the image.
- [x] The options should be disabled from users being able to reselect.
- [x] The next arrow will appear below the multiple choice.
- [x] The arrow placement should follow the placement on desktop as it does on mobile.
- [x] The options should be locked from users being able to reselect.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
