### ISSUE TITLE
User can continue to the next picture if correct

### ISSUE THREAD

**Issue by annaaksenov** [annaaksenov/PurrBreeds#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to continue onto the next image.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking next will display a new cat image and new 3 multiple choices.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Replace the current cat image with a new one.
- [x] Unlock the choices.
- [x] Remove the next arrow.
- [x] Curate two new incorrect options and one true option.
- [x] Make sure that click targets are `<input>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] The filler options should not duplicate the correct answer.
- [x] Fixate the quiz so it does not move down when the banner pops up.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
